services:
  minio:
    image: minio/minio:RELEASE.2025-02-18T16-25-55Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
      MINIO_REGION_NAME: us-east-1
      MINIO_REGION: us-east-1
    command: server /data --console-address :9001
    volumes:
      - ./minio-data:/data
      - ./init-minio.sh:/init-minio.sh
    stdin_open: true
    tty: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      lakehouse-network:

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nessie
      POSTGRES_PASSWORD: nessie
      POSTGRES_DB: nessie
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      lakehouse-network:

  nessie:
    image: projectnessie/nessie:0.75.0
    container_name: nessie
    ports:
      - "19120:19120"
    environment:
      NESSIE_VERSION_STORE_TYPE: JDBC2
      NESSIE_VERSION_STORE_PERSIST_JDBC_DATASOURCE: postgresql
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgres:5432/nessie"
      QUARKUS_DATASOURCE_USERNAME: "nessie"
      QUARKUS_DATASOURCE_PASSWORD: "nessie"
      NESSIE_SERVER_AUTHENTICATION_ENABLED: false
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ./nessie-data:/nessie/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:19120/api/v1/config || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      lakehouse-network:

  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:25.1
    container_name: dremio
    ports:
      - "9047:9047"
      - "31010:31010" 
      - "32010:32010"
      - "45678:45678"
    volumes:
      - ./dremio-data:/opt/dremio/data
    restart: always
    networks:
      lakehouse-network:
  
  spark-master:
    image: bitnami/spark:3.5.1
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      SPARK_MODE: master
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT: 7077
      AWS_REGION: us-east-1
    volumes:
      - ./spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./scripts:/opt/bitnami/spark/scripts
    stdin_open: true
    tty: true
    restart: always
    networks:
      lakehouse-network:
  
  spark-worker:
    image: bitnami/spark:3.5.1
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2G
    stdin_open: true
    tty: true
    restart: always
    networks:
      lakehouse-network:

networks:
  lakehouse-network: